source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'GFBS' do 

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "DOPDropDownMenu-Enhanced"
pod "Masonry"
pod "SDCycleScrollView"
pod "LTNavigationBar"

pod "MMSProfileImagePicker" 
pod 'LLImagePickerView'
pod 'RSKImageCropper'

pod "DACircularProgress"
pod "pop"
pod 'GoogleSignIn'
pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end 
