source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"



pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "DOPDropDownMenu-Enhanced"
pod "Masonry"
pod "SDCycleScrollView"
pod "LTNavigationBar"

pod 'LLImagePickerView'
pod 'RSKImageCropper'

pod "DACircularProgress"
pod "pop"
pod 'GoogleSignIn'

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

pod 'JPush'
pod 'CocoaLumberjack'

target :"GFBS" 
